version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - FLASK_APP=app_flask.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env.development
    command: flask run --host=0.0.0.0 --reload

  # Add more services as needed (e.g., database, cache, etc.) 