version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python app_flask.py

  celery-worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A celery_config worker --loglevel=info --concurrency=4

  celery-beat:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A celery_config beat --loglevel=info

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A celery_config flower --port=5555

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 